#ifndef PHP_COMPILER_MACROS_H
#define PHP_COMPILER_MACROS_H

#define DISABLE_ALL_LOGS
#define DISABLE_BYTECODE_EXECUTION

/* System debug */
#define CONSOLE_SYSTEM_LOG_ENABLED

/* Node debug */
#define CONSOLE_NODE_LOG_ENABLED
#define NODE_DOT_LABEL_DEBUG
// #define NODE_FILE_GENERATION_DEBUG

/* Parser debug */
#define CONSOLE_PARSER_LOG_ENABLED

/* Lexer debug */
#define CONSOLE_LEXER_LOG_ENABLED
#define CONSOLE_STATESTREE_LOG_ENABLED
// #define CONSOLE_TOKENQUEUE_LOG_ENABLED
// #define CONSOLE_INDENTTRACKER_LOG_ENABLED
// #define CONSOLE_BUFFER_LOG_ENABLED


#endif //PHP_COMPILER_MACROS_H
